[theme]
theme = "native"
[icons]
icons = "awesome"

[[block]]
block = "battery"
interval = 5

[[block]]
block = "sound"
driver = "pulseaudio"

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source"

[[block]]
block = "memory"
format = " $icon $mem_used.eng(3,B,M) "
interval = 5 

[[block]]
block = "net"
interval = 3
[[block.click]]
button = "left"
cmd = "foot -e nmtui"

[[block]]
block = "keyboard_layout"
driver = "sway"
[block.mappings]
"English (US)" = "🇺🇸"
"Ukrainian (N/A)" = "🇺🇦"

[[block]]
block = "temperature"
interval = 10
format = " $icon {$average}C "

[[block]]
block = "time"
format = " %a %r "
interval = 1 

[[block]]
block = "notify"
driver = "swaync"


